### ISSUE TITLE
Should "%" and some symbols and punctuation characters be `N`?

### ISSUE THREAD

**Issue by kojiishi** [kojiishi/unicode-auto-spacing#11]
@xfq I remember you were talking about making "%" to `N`, is that correct?

I was looking at [U+0025 Percent Sign](https://codepoints.net/U+0025), its Script is Common and General Category is Other Punctuation. Including [all Other Punctuation](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%3APo%3A%5D&g=&i=) is probably more than what we want.

Another option is to make this an exception, by including a code point. Would you like that?

Do you have other list of code points you want to make exceptions?

/cc @kidayasuo

**Comment by kojiishi** [comment]
Existing implementations/spec:
| Name | Value |
|---|---|
| Apple platforms | `N` |
| MS Word | `O` |
| CSS | `O` |

**Comment by kojiishi** [comment]
See also:
* https://github.com/w3c/csswg-drafts/issues/9479#issuecomment-1803450386
* #12

**Comment by kojiishi** [comment]
As far as I tested symbols and punctuation characters in Basic Latin, the Apple platforms inserts the spacing:
* To both sides of `%`, `+`, `/`, `@`, `{`, `|`, `}`, `~`
* To the left of '('
* To the right of `'`, ')'
[Latin 1 Supplement](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%3ABlock%3DLatin+1+Supplement%3A%5D%26%5B%5B%3AP%3A%5D%5B%3AS%3A%5D%5D&g=&i=gc):
* To both sides of `¡`, `¢`, `£`, `§`, `«`, `¬`, `±`,  `µ`, `¶`, `·`, `»`, `¤`, `¥`, `¼`, `¿`, `×`, `÷`
Note the spacing is observed on both sides of `²`, `³`, `¹`, `½`, `¾` so [`No`](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%3ABlock%3DLatin+1+Supplement%3A%5D%26%5B%3AN%3A%5D&g=&i=gc) may be also `N`.

**Comment by xfq** [comment]
IMHO most of the "Other Punctuation" code points should be N, but there are some exceptions, like:

* `U+00B7 MIDDLE DOT [·]` should be `O`, because it is a [Chinese punctuation mark](https://www.w3.org/TR/clreq/#id86);
* `U+2026 HORIZONTAL ELLIPSIS […]` should be `O`. It is a Chinese/Japanese punctuation mark;
* `*`  should be `O`. When it is used for footnote marks, ベタ組とします;
* `/` should probably be `O` too, but the clreq group doesn't have strong opinion on this;
* [Small Form Variants](https://en.wikipedia.org/wiki/Small_Form_Variants) should be `O`, because they are Chinese punctuation marks.

-----

Alternatively, we can use a more conservative approach, which is to make all symbols default to `O`, and then adjust some of them (like the Basic Latin characters) to `N`.

Here is a list of `N`-list from some libraries:

* [pangu.js](https://github.com/vinta/pangu.js/blob/6107055384b99e6f30a49f5d1b85aa0b78251dc2/src/shared/core.js#L25)
* [text-autospace.js](https://github.com/mastermay/text-autospace.js/blob/65fec37e319f6fdc21109647aa861948be51c55d/text-autospace.js#L6-L10)
* [zhlint](https://github.com/zhlint-project/zhlint/blob/a44792567bc099d459fd8b1a57f46bf01e5b8dcf/src/parser/char.ts#L26C1-L26C1)

**Comment by kojiishi** [comment]
Thanks for clarifying your thoughts, it's really appreciated.

> IMHO most of the "Other Punctuation" code points should be N, but there are some exceptions

I think I was misunderstanding, because I was incorrectly assuming you wanted to pick up some from `Po`, but now I understand your words a lot better.

With the correct understanding, this is a lot more code points than Apple does, and more than what Microsoft/Google Japanese style guides define. In the current Unicode, [there are 628 code points in Po](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%3APo%3A%5D&g=&i=). Are you sure you want to make all of them to `N`, other than you listed above?

For example from "4.1.11 Symbols & spaces" of [Microsoft Japanese Style Guide](https://download.microsoft.com/download/a/8/2/a822a118-18d4-4429-b857-1b65ab388315/jpn-jpn-StyleGuide.pdf):
> Between characters, a space should be inserted as follows.
> 1. Between full-width and half-width characters
> Exceptionally, do not insert a space in the following cases:
> * Between ideographic full stop (。)/ideographic comma (、) and a half-width character
> * Between a numeral and unit of angle (°)
> * On each side of text enclosed by parentheses/quotation marks/brackets
> * On each side of slash
> * Between a full-width character and question mark (?)/exclamation mark (!)/colon
(:)/ellipses (...) that ends the term
> * Between a character and access key enclosed by parentheses in the user interface

The "4.2.10 Spacing" of the [Microsoft Traditional Chinese Style Guide](https://download.microsoft.com/download/2/9/3/293e6d41-ba40-451b-a41e-94bdb6242ae3/zho-twn-StyleGuide.pdf) says:
> Half-width space needed between Chinese characters and English letters or numbers
> Half-width space needed between Chinese characters and half-width punctuations: ( ), [ ]

I'm afraid including all `Po` has undesired cases. Now that I understand your intention, I'll think about possible side effects, but it's great if you can review the list of [all `Po`](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%3APo%3A%5D&g=&i=) to see if it matches the behavior you want.

**Comment by kojiishi** [comment]
I've prepared [a diff for your proposal](https://github.com/kojiishi/unicode-auto-spacing/pull/15/files). Great if you can double check it describes what you intend.

**Comment by xfq** [comment]
> Thanks for clarifying your thoughts, it's really appreciated.
> 
> > IMHO most of the "Other Punctuation" code points should be N, but there are some exceptions
> 
> I think I was misunderstanding, because I was incorrectly assuming you wanted to pick up some from `Po`, but now I understand your words a lot better.
> 
> With the correct understanding, this is a lot more code points than Apple does, and more than what Microsoft/Google Japanese style guides define. In the current Unicode, [there are 628 code points in Po](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%3APo%3A%5D&g=&i=). Are you sure you want to make all of them to `N`, other than you listed above?

I thought so at first, but now that I think about it, to reduce the possibility of potential compatibility issues, a more conservative approach may be more appropriate, because it is easier to change O into N than to change N into O (the latter may have potential risk of compatibility issues).

That said, I will review the code points in #15. Even if we choose to use a conservative approach, I think it is beneficial to have a look at other `Po` code points to see if we need to change any of them to N.

**Comment by kojiishi** [comment]
I updated the PR #15:
* Reflected manual review results with @xfq
* Renamed the value from `N` to `CN`.

Reviews and comments are appreciated if interested in which punctuation characters to include to the `CN` value (name TBD). The [data diff is here](https://github.com/kojiishi/unicode-auto-spacing/pull/15/files).

**Comment by kidayasuo** [comment]
JLReq TF will review it. I would like to make the logic to be as simple as possible, provided it remains reasonable. With that in mind, we would like to review the CN candidates to determine if it's feasible to classify them, or a portion of them, as just N.

In our past discussions, we identified examples that are largely consistent, such as the relationship between Kanji and Latin scripts. However, we also encountered instances with mixed cases. The handling of Latin punctuation might fall into this latter category.

During discussions, we must always be mindful that this table is the fallback default. I also believe it should remain conservative because, for the end user, removing extra spaces is more difficult than inserting them.

**Comment by kidayasuo** [comment]
> As far as I tested symbols and punctuation characters in Basic Latin, the Apple platforms inserts the spacing:
> 
> * To the left of `(`
> * To the right of `'`, `)`

This reminded me of one of the reasons why we opted to classify most punctuations as 'O'. Some punctuations, like parentheses and curly quotes like we see with the examples above, have directionality. If we decide to add default spacing for them, we might want the space to be on only one side. It adds complexity.

Together with the policy that we would like to be conservative because users can always insert a space, we opted to make them all 'O'.

**Comment by kojiishi** [comment]
Please use https://github.com/unicode-org/unicodetools/issues/764 for further comments.

**Comment by kojiishi** [comment]
Closed at https://github.com/unicode-org/unicodetools/issues/764.

**Comment by yisibl** [comment]
@vitorroriz is in the process of implementing the text-autospace property for WebKit, and I thought he could make some comments.

https://github.com/WebKit/WebKit/pull/32261

**Comment by kidayasuo** [comment]
> @vitorroriz is in the process of implementing the text-autospace property for WebKit, and I thought he could make some comments.

I trust that this implementation aligns with the “EAST ASIAN AUTO SPACING” proposal: https://www.unicode.org/L2/L2024/24057r-auto-spacing-prop.pdf
